model_list:
  - model_name: gemini-3-pro-preview
    litellm_params:
      model: gemini/gemini-3-pro-preview
      api_key: os.environ/GEMINI_API_KEY


general_settings:
  master_key: sk-1234
  ui_access_mode: all 
  # database_url: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
  store_model_in_db: true

litellm_settings:
  success_callback: ["langfuse"] # Hier geschieht die Magie
  failure_callback: ["langfuse"] # Optional: Loggt auch Fehler